### ISSUE TITLE
Commit hash?

### ISSUE THREAD

**Issue by 3usi9** [CoderEval/CoderEval#7]
Hi,
I'm trying to replicate the dataset construction process, but I am encountering difficulties in locating the commit hashes for each cloned repository in the dataset. Are these details included in the dataset?

**Comment by yh1105** [comment]
Sorry, I did not store the commit hash for each repo. You can refer to the following content. If I still cannot solve your problem, I will take the time to confirm the commit hash.


Best,
Hao


——————————————————————————————————————————
Thank you for your great question.


To be honest, the current open-source version of CoderEval is a re-implemented version after I left my internship company. When I implemented it, I also noticed that some projects had undergone version changes.

The example in your email is belong to plib_runnable level, it can be executed without relying on the project, so I execute it separately. You can see this in the standalone folder in the Docker environment.


Since your example is executable independently of the project environment, I did not find any inconsistency between the version of gopad-python in the Docker environment and when I interned at the company.


I have confirmed that you can find the version in the following project on gopad python:

https://github.com/gopad/gopad-python/tree/3c0460de7efc383436d5c77223d05be62367311a



What I can guarantee is that all projects in the Docker environment (except those that do not rely on the project environment for execution) are currently available. Functions that do not rely on the project environment and can be executed are not affected by the project version.


If you really need an accurate project version for the functions that does not rely on the project environment, I can help you with some filtering.


You can also add my WeChat: yuhao210203, I can call to help you.

Best,

Hao



-----原始邮件-----

发送时间:2023-11-10 10:50:17 (星期五)
收件人: 于浩 <[yh0315@pku.edu.cn](mailto:yh0315@pku.edu.cn)>
抄送:
主题: Re: Request for Sharing Backup of Repositories Selected by CoderEval

Dear Hao,

 

I hope this message finds you well. I want to express my gratitude for your previous response.

 

 I am currently in need of the original projects for CoderEval. However, I have noticed that some of the Python projects on the GitHub repository, such as "gopad---gopad-python(https://github.com/gopad/gopad-python)"， do not seem to include any Python files. Additionally, it appears that the Docker environment for CodeEval does not provide access to all the original projects. 

 

In light of thses, I want to kindly inquire whether you might have access to backups of the original projects. Your assistance in this matter would be greatly appreciated.

 

Thanks again.

 

Warm regards,



 
 
------------------ Original ------------------
From:  "于浩"<[yh0315@pku.edu.cn](mailto:yh0315@pku.edu.cn)>;
Date:  Fri, Nov 10, 2023 07:05 AM

Subject:  Re: Request for Sharing Backup of Repositories Selected by CoderEval
 


We public the docker environment for CoderEval now. All projects we used for CoderEval are in the docker environment. You can find the link in the GitHub repo, or you can access the follow link to get CoderEval docker environment directly.

[https://drive.google.com/file/d/1PAFFcXQaC1qxXmsLWJNL0z7izQP5VcrR/view?usp=sharing](https://drive.google.com/drive/folders/11Ox27cV4spP-_ly-GK6qAh6EG7TxwYh1?usp=sharing)


If you have any questions, please let me know.



Best,

Hao




-----原始邮件-----

发送时间:2023-11-09 21:01:18 (星期四)
收件人: yh0315 <[yh0315@pku.edu.cn](mailto:yh0315@pku.edu.cn)>
抄送:
主题: Request for Sharing Backup of Repositories Selected by CoderEval

Dear Hao Yu,

I hope this letter finds you well. I am writing to express my gratitude for your remarkable work on CoderEval, which I find incredibly valuable and captivating. Please allow me to introduce myself: I am a doctoral student from Sun Yet-sen University, and I am eager to employ CoderEval to evaluate my own methods.


During the process, I encountered a challenge when attempting to download the GitHub repositories selected by CoderEval. Some repositories have undergone changes. Therefore, I would like to inquire whether you have a backup of the repositories chosen for CoderEval and it is anticipated that you could share them with me.


I genuinely appreciate your assistance and look forward to your favorable response. May your research endeavors progress smoothly.


Thank you very much.

**Comment by 3usi9** [comment]
Thanks for your prompt response. I have located the project source within the Docker image.
